# (c) William Belle, 2021.
# See the LICENSE file for more details.

name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Node.js ${{ matrix.node }} CI

    strategy:
      fail-fast: false
      matrix:
        node: [ '10', '12', '14', '15' ]

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install and test
        run: |
          npm i
          npm t
